# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs: 
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    timeoutInMinutes: 1200

    steps:
      - task: CmdLine@2
        name: build
        inputs:
          script: |
            ls -al
            bash ./.install/linux/faceswap_setup_x64.sh
          workingDirectory: '$(Agent.BuildDirectory)/s'


