# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs: 
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    timeoutInMinutes: 1200

    steps:
      - task: CmdLine@2
        name: build
        inputs:
          script: |
            echo $HOME
            ls -al
            echo $pwd
            yes | bash ./s/.install/linux/faceswap_setup_x64.sh
            ls -al ./s
            ls -al ./y
            ls -al
            echo $HOME/miniconda3
          workingDirectory: '$(Agent.BuildDirectory)'


